name: Playwright Repmove Tests
on:
  push:
    branches: [ master ]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      VALID_EMAIL: ${{ secrets.VALID_EMAIL }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
    - name: Deploy Playwright report to GitHub Pages
    if: always()
    uses: peaceiris/actions-gh-pages@v4
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_branch: gh-pages
      publish_dir: playwright-report
      force_orphan: true